version: '3.8'

services:
  mysql:
    container_name: dbTodos
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ToDos
      MYSQL_USER: SA
      MYSQL_PASSWORD: SA
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - service-net-app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 25

  app-todos:
    container_name: app-todos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbTodos:3306/ToDos
      SPRING_DATASOURCE_USERNAME: SA
      SPRING_DATASOURCE_PASSWORD: SA
    depends_on:
      mysql:
          condition: service_healthy
    networks:
      - service-net-app


networks:
  service-net-app:
volumes:
  mysql-data: